### ISSUE TITLE
README

### ISSUE THREAD

**Issue by wakayama-kazuma** [wakayama-kazuma/dateplaner#1]
DatePlaner
■サービス概要
オススメのデートスポットや知っている穴場スポットから1日デートプランを作成し共有するサービスです。 もちろんデートだけでなく観光にオススメな穴場スポットやランチスポットなどオススメスポットであれば、どんなコンセプトでも投稿できます！

■ このサービスへの思い・作りたい理由
元々一人暮らしだったため、おうちデートが多くあまり気になりませんでしたが、実家に帰ると外でのデートが多くなり１日のデートプランを考えるのが割と大変だと感じました。 そのため投稿されたデートプランをもとに計画を練ったり穴場スポットを知れたら便利だと思いました。

■ ユーザー層について
デートプランを考えるのが面倒な人
穴場スポットを知りたい人
■ サービスの利用イメージ
気になる投稿をもとに計画を練り実行。 その後そのプラン投稿することで自分のストックとして扱うことができ他の人も参考にすることができる。

■ ユーザーの獲得について
SNSを活用する：twitterで投稿できるようにする

■ サービスの差別化ポイント・推しポイント
デートや穴場スポットを紹介する場はあるがデートプランそのものを投稿する場は見かけない

■ 機能候補
MVPリリース
ユーザー登録機能
ログイン・ログアウト機能
Googleアカウントログイン・ログアウト機能
パスワード再設定機能
デート、穴場スポット新規登録・編集機能
モデルコース新規投稿・編集機能
スポットごとの観光時間・移動手段設定機能
プロフィール表示・編集機能
いいね機能
お気に入り機能・お気に入り一覧
自分の投稿履歴機能
Twitter共有機能
ランキング機能
本リリース
オートコンプリート検索・絞り込み検索機能
観光地・My穴場スポットの詳細ページにGoogleMap表示機能

**Comment by kenchasonakai** [comment]
issueではなくプルリクエストを作成して提出していただきますようお願いいたします
